version: "3.7"

# 申明同一个网络
networks:
  mattermostnet:
    name: mattermostnet

volumes:
  mattermostwebdata:
    name: mattermostwebdata

services:
  db:
    image: mattermost/mattermost-prod-db
    read_only: true
    restart: unless-stopped
    networks:
      mattermostnet:
    volumes:
      - ./volumes/db/var/lib/postgresql/data:/var/lib/postgresql/data
      - ./volumes/db/var/run/postgresql:/var/run/postgresql
      - ./volumes/db/etc/wal-e.d/env:/etc/wal-e.d/env
      - ./volumes/db/tmp:/tmp
      - ./volumes/db/usr/share/postgresql:/usr/share/postgresql
      - /etc/localtime:/etc/localtime:ro
    environment:
      - POSTGRES_USER=mmuser
      - POSTGRES_PASSWORD=mmuser_password
      - POSTGRES_DB=mattermost
    # uncomment the following to enable backup
    #  - AWS_ACCESS_KEY_ID=XXXX
    #  - AWS_SECRET_ACCESS_KEY=XXXX
    #  - WALE_S3_PREFIX=s3://BUCKET_NAME/PATH
    #  - AWS_REGION=us-east-1

  app:
    image: mattermost/mattermost-prod-app
    # uncomment following lines for team edition or change UID/GID
    # args:
    #   #   - edition=team
    #   - PUID=1000
    #   - PGID=1000
    restart: unless-stopped
    networks:
      mattermostnet:
    volumes:
      - ./volumes/app/config:/mattermost/config:rw
      - ./volumes/app/data:/mattermost/data:rw
      - ./volumes/app/logs:/mattermost/logs:rw
      - ./volumes/app/plugins:/mattermost/plugins:rw
      - ./volumes/app/client-plugins:/mattermost/client/plugins:rw
      - /etc/localtime:/etc/localtime:ro
    environment:
      # set same as db credentials and dbname
      - MM_USERNAME=mmuser
      - MM_PASSWORD=mmuser_password
      - MM_DBNAME=mattermost

      # use the credentials you've set above, in the format:
      # MM_SQLSETTINGS_DATASOURCE=postgres://${MM_USERNAME}:${MM_PASSWORD}@db:5432/${MM_DBNAME}?sslmode=disable&connect_timeout=10
      - MM_SQLSETTINGS_DATASOURCE=postgres://mmuser:mmuser_password@db:5432/mattermost?sslmode=disable&connect_timeout=10

      # in case your config is not in default location
      #- MM_CONFIG=/mattermost/config/config.json

  web:
    image: mattermost/mattermost-prod-web
    ports:
      - "7080:80"
      - "7443:443"
    read_only: true
    restart: unless-stopped
    networks:
      mattermostnet:
    volumes:
      # This directory must have cert files if you want to enable SSL
      # - ./volumes/web/conf.d/mattermost.conf:/etc/nginx/conf.d/mattermost.conf
      - ./volumes/web/nginx.conf:/etc/nginx/nginx.conf
      - ./volumes/web/log/:/var/log/nginx/:rw
      - ./volumes/web/cert:/cert:ro
      - /etc/localtime:/etc/localtime:ro
      - mattermostwebdata:/var/cache/nginx
      - mattermostwebdata:/var/run
    # Uncomment for SSL
    # environment:
    #  - MATTERMOST_ENABLE_SSL=true
